INSERT INTO STUDENT_TABLE(STID, NAME, SURNAME) VALUES (1, 'Janis', 'Liepins');
INSERT INTO STUDENT_TABLE(STID, NAME, SURNAME) VALUES (2, 'Baiba', 'Jauka');
INSERT INTO STUDENT_TABLE(STID, NAME, SURNAME) VALUES (3, 'Liena', 'Nejauka');